// solid-tests/src/components/chat-message.tsx
import { Component } from "solid-js";
import { CMessage } from "../types";

export type ChatMessageProps = {
  message: CMessage;
};

const ChatMessage: Component<ChatMessageProps> = ({ message }) => {
  console.log("Rendered message", message);
  return (
    <div class="chat-message">
      <span style={{ color: message.color }}>{message.user.name}</span>{" "}
      <span>{message.message}</span>
    </div>
  );
};

export default ChatMessage;

// svelte-tests/src/lib/ChatMessage.svelte
<script lang="ts">
  import type { CMessage } from "../app-types";

  console.log("RENDER MESSAGE");
  export let message: CMessage;
  export let onCustomHover: () => void = undefined;
</script>

<div on:mouseenter={onCustomHover} class="chat-message">
  <span style:color={message.color}>{message.user.name}</span>
  <span>{message.message}</span>
</div>
