// svelte-tests/src/lib/ChatFooter.svelte
<script lang="ts">
  import { api } from "../App.svelte";


  let chatInput = "";

  const handleSend = () => {
    api.sendMessage(chatInput, userName);
    chatInput = "";
  }
  export let userName: string;
</script>

<input
  bind:value={chatInput}
  class="chat-input"
  type="text"
  placeholder="Type Your Message"
/>
<button on:click={handleSend}>Send</button>

// vue-tests/src/components/ChatFooter.vue
<script lang="ts" setup>
import { inject, ref } from "vue";
import type { SendMessage } from "../types";

const sendMessage = inject<SendMessage>("sendMessage") ?? (() => null);
const chatInput = ref("");
</script>

<template>
  <input
    v-model="chatInput"
    class="chat-input"
    type="text"
    placeholder="Type Your Message"
  />
  <button @click="sendMessage(chatInput)">Send</button>
</template>
