// vue-tests/src/components/ChatMessage.vue
<script lang="ts" setup>
import { defineProps } from "vue";
import type { CMessage } from "../types";

const props = defineProps<{ message: CMessage }>();
</script>

<template>
  <div class="chat-message">
    <span :style="{ color: props.message.color }">
      {{ props.message.user.name }}
    </span>
    <span>
      {{ props.message.message }}
    </span>
  </div>
</template>

// solid-tests/src/components/chat-message.tsx
import { Component } from "solid-js";
import clsx from "clsx";
import { CMessage } from "../types";

export type ChatMessageProps = {
  message: CMessage;
};

const ChatMessage: Component<ChatMessageProps> = ({ message }) => {
  return (
    <div
      class={clsx("chat-message", {
        ["chat-message__admin"]: message.type === "admin-message",
      })}
    >
      <span style={{ color: message.color }}>{message.user.name}</span>{" "}
      <span>{message.message}</span>
    </div>
  );
};

export default ChatMessage;
