// solid-tests/src/index.tsx
/* @refresh reload */
import { render } from "solid-js/web";

import "./index.scss";
import App from "./App";
import { ChatWsContextProvider } from "./contexts/chat-ws-context";

render(
  () => (
    <ChatWsContextProvider>
      <App />
    </ChatWsContextProvider>
  ),
  document.getElementById("root") as HTMLElement
);

// react-tests/src/main.tsx
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import { ChatWsContextProvider } from "./chat-ws-context";
import "./index.css";

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <ChatWsContextProvider>
      <App />
    </ChatWsContextProvider>
  </React.StrictMode>
);
